# Generated by Django 3.2.25 on 2025-11-28 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_operator_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
