# Generated by Django 3.2.25 on 2025-11-16 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_auto_20250323_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2027, 11, 16, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operator',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2027, 11, 16, 0, 0, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='RIDModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rid_id', models.UUIDField(editable=False, help_text='RID ID (UUID v4) broadcast by the module', unique=True)),
                ('module_esn', models.CharField(help_text='Electronic Serial Number', max_length=16, unique=True)),
                ('module_port', models.CharField(blank=True, help_text='USB port (COM3, /dev/ttyACM0, etc.)', max_length=50, null=True)),
                ('module_type', models.CharField(default='ESP32-S3', help_text='Module type/model', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned'), ('lost', 'Lost')], default='active', max_length=20)),
                ('activation_status', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], default='temporary', max_length=20)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time module was detected', null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When module was deactivated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes', null=True)),
                ('firmware_version', models.CharField(blank=True, help_text='Firmware version if tracked', max_length=20, null=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rid_modules', to='registry.aircraft')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rid_modules', to='registry.operator')),
            ],
            options={
                'verbose_name': 'RID Module',
                'verbose_name_plural': 'RID Modules',
                'db_table': 'rid_modules',
            },
        ),
        migrations.AddIndex(
            model_name='ridmodule',
            index=models.Index(fields=['operator'], name='rid_modules_operato_124025_idx'),
        ),
        migrations.AddIndex(
            model_name='ridmodule',
            index=models.Index(fields=['aircraft'], name='rid_modules_aircraf_84043b_idx'),
        ),
        migrations.AddIndex(
            model_name='ridmodule',
            index=models.Index(fields=['status'], name='rid_modules_status_83095a_idx'),
        ),
        migrations.AddIndex(
            model_name='ridmodule',
            index=models.Index(fields=['module_esn'], name='rid_modules_module__aca0df_idx'),
        ),
        migrations.AddIndex(
            model_name='ridmodule',
            index=models.Index(fields=['rid_id'], name='rid_modules_rid_id_c75099_idx'),
        ),
    ]
